---
apiVersion: v1
kind: Service
metadata:
  name: api-port
spec:
  ports:
    - port: 5000
      protocol: TCP
      targetPort: 5000
  selector:
    name: api
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  selector:
    matchLabels:
      name: api
  replicas: 3
  template:
      metadata:
        labels:
          name: api
      spec:
        containers:
          - name: api
            image: hello-world
            # TODO add env, this env file is 10 lines
            ports:
              - containerPort: 5000
            # volumes will also be needed
        imagePullSecrets:
          - name: regcred
        restartPolicy: Always
