apiVersion: v1
kind: Service
metadata:
  name: api-port
spec:
  ports:
    - port: 5000
      protocol: TCP
      targetPort: 5000
  selector:
    name: api
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  selector:
    matchLabels:
      name: api
  template:
      metadata:
        labels:
          name: api
      spec:
        containers:
          - name: api
            image: piotrostr/api
            envFrom:
              - secretRef:
                  name: api-secrets
                  optional: False
            ports:
              - containerPort: 5000
            resources:
              requests:
                cpu: "2800m"
                memory: "2800Mi"
              limits:
                cpu: "3800m"
                memory: "3800Mi"
        imagePullSecrets:
          - name: regcred
        restartPolicy: Always
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api
  minReplicas: 2
  maxReplicas: 5
