apiVersion: v1
kind: Service
metadata:
  name: interface
  labels:
    app: app
spec:
  type: NodePort
  ports:
  - port: 3000
    name: http
    nodePort: 30080
  selector:
    app: app
---
apiVersion: v1
kind: Deployment
metadata:
  name: interface
spec:
  selector:
    matchLabels:
      name: interface
  replicas: 1
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: interface
        image: piotrostr/interface
        ports:
        - containerPort: 3000
